// Program: ablashell.c
// Programmer: Ablasse Kingcaid-Ouedraogo
// Assignment: Project 1
// Purpose: A shell implementation in C
source = ablashell.c
target = ablashell
all:
	gcc -o $(target) $(source)
